### ISSUE TITLE
Add library.json for platformio.org

### ISSUE THREAD

**Issue by karrots** [LowPowerLab/SFE_BMP180#1]
Same as on wireless programming library.

**Comment by LowPowerLab** [comment]
Done

**Comment by karrots** [comment]
Closed by 2aa1f671ad4e853c1dc2204d01929d85174626e6

**Comment by karrots** [comment]
This library now shows in platformio. I ran the register lib command yesterday. Today he added it.

**Comment by LowPowerLab** [comment]
Great!
