### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [LowPowerLab/SFE_BMP180#3]
When you improve the SFE_BMP180.cpp, you might just as well remove this line: `while(Wire.available() != length) ; // wait until bytes are ready`

There is no need to wait after a Wire.requestFrom().
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

See also this issue: https://github.com/sparkfun/BMP180_Breakout_Arduino_Library/issues/3

**Comment by LowPowerLab** [comment]
Removed, thank you!
